### ISSUE TITLE
Missing folders reported, not matching the quickstart guide

### ISSUE THREAD

**Issue by TheAncientGoat** [awatson1978/clinical-nightwatch#13]
Nightwatch complains about missing commands/components and commands/methods directories on first run; did I do something wrong or should the guide be updated?

**Comment by awatson1978** [comment]
Sounds like you didn't configure the filesystem correctly.  Try using the following starrynight command, which should copy the correct directories and files into the correct locations:

````
starrynight sample acceptance
```

I'm still working out the API for starrynight.  Right now ``acceptance`` is basically just a synonym for ``nightwatch``.

**Comment by ryanswrt** [comment]
Thanks for replying so quick! Funny that I didn't see starrynight, I tried to find as many testing frameworks and even checked your github for other repos, must have stumbled over it. 

The current readme of nightwatch doesn't specify creating the components and methods subdirectories under commands though, but yeah, not much point in updating it seeing as the package is being deprecated

**Comment by awatson1978** [comment]
StarryNight is only a couple of weeks old.  I only just cracked the code on how to spawn/exec libraries in node, and how to launch and run nightwatch and selenium, etc. etc.  Been researching it for almost a year though, trying to figure out what **to** do, which made the _how_ a lot easier.  It's really rocking-and-rolling, though.  The happy culmination of a year's worth of work!
