### ISSUE TITLE
Selenium fails to connect by default

### ISSUE THREAD

**Issue by TheAncientGoat** [awatson1978/clinical-nightwatch#14]
I'm not sure if this is a mis-configuration, but following the guide, Firefox starts and maintains a blank page, indicating that the Selenium connection is failing. I manually grabbed the Selenium jar from the project's website and put it in my project's root, following the Nightwatch instructions, and it worked after that (although I had to re-write the runner bash file because the default Nightwatch config tries to open IE, which is unfortunately not available on Linux...)

Should this be reflected in the docs or am I doing something wrong?

**Comment by awatson1978** [comment]
Yeah, sounds like you're following the Nightwatch.js instructions, and not the clinical:nightwatch instructions.  And Nightwatch defaults to Firefox, so I have no idea how you got it to try to open IE.  

Try using the StarryNight utility, as this package is being deprecated.  Thanks.
