### ISSUE TITLE
Migration plan?

### ISSUE THREAD

**Issue by christieewen** [awatson1978/clinical-nightwatch#16]
Is http://clinical.meteor.com/ hosted on meteor's free tier?  If so, it needs to be migrated asap before March 25th noon Pacific time.  I'm thinking about hosting a migration party early Friday morning :) j/k ... thinking about it.

**Comment by awatson1978** [comment]
I've been busy at work all last week!  Everything is moved over to Galaxy!

**Comment by christieewen** [comment]
Cool!  In that case, I'll close this issue.
